
# Conexão com MYSQL
spring.application.name=backend
spring.datasource.url = jdbc:mysql://localhost:3306/notelab?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


## JPA / Hibernate
# update -> atualizar a schema da tabela sem apagar os dados
# create -> toda vez que a aplicação iniciar ele recria a tabela (apaga tudo)
# validate -> só valida se o código java esta´igual a tabela no banco
# none -> desativa o gerenciamento de mundaça automático

spring.jpa.hibernate.ddl-auto=update
# Mostra o sql que foi executado no terminal
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
