#spring.application.name=backend
#
#server.port=${PORT:8080}
#
#spring.datasource.url=${DB_URL:jdbc:postgresql://aws-1-us-east-1.pooler.supabase.com:6543/postgres}
#spring.datasource.username=${DB_USERNAME:postgres.vhtxdirsjdkqzbaesuup}
#spring.datasource.password=${DB_PASSWORD}
#spring.datasource.driver-class-name=org.postgresql.Driver
#spring.datasource.hikari.data-source-properties.sslmode=require
#spring.datasource.hikari.data-source-properties.prepareThreshold=0
#
#server.servlet.encoding.charset=UTF-8
#server.servlet.encoding.enabled=true
#server.servlet.encoding.force=true
#server.tomcat.uri-encoding=UTF-8
#spring.thymeleaf.encoding=UTF-8
#spring.thymeleaf.cache=true
#
#server.error.include-message=always
#
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.application.name=backend

server.port=${PORT:8080}

spring.datasource.url=${DB_URL:jdbc:postgresql://aws-1-us-east-1.pooler.supabase.com:6543/postgres}
spring.datasource.username=${DB_USERNAME:postgres.vhtxdirsjdkqzbaesuup}
spring.datasource.password=${DB_PASSWORD}

spring.datasource.driver-class-name=org.postgresql.Driver

spring.datasource.hikari.data-source-properties.sslmode=require
spring.datasource.hikari.data-source-properties.prepareThreshold=0
spring.datasource.hikari.maximum-pool-size=3

server.servlet.encoding.charset=UTF-8
server.servlet.encoding.enabled=true
server.servlet.encoding.force=true
server.tomcat.uri-encoding=UTF-8

spring.thymeleaf.encoding=UTF-8
spring.thymeleaf.cache=true

server.error.include-message=always

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true