# Conexão com MySQL
spring.application.name=backend
spring.datasource.url=jdbc:mysql://localhost:3306/notelab?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=UTF-8&connectionCollation=utf8mb4_unicode_ci
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

server.servlet.encoding.charset=UTF-8
server.servlet.encoding.enabled=true
server.servlet.encoding.force=true
server.tomcat.uri-encoding=UTF-8
spring.thymeleaf.encoding=UTF-8

## JPA / Hibernate
# update -> atualizar a schema da tabela sem apagar os dados
# create -> toda vez que a aplicação iniciar ele recria a tabela (apaga tudo)
# validate -> só valida se o código Java está igual à tabela no banco
# none -> desativa o gerenciamento de mudança automático
spring.jpa.hibernate.ddl-auto=update
# Mostra o SQL que foi executado no terminal
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
